baseURL = "https://tree123.org/"
languageCode = "en-us"
title = "WeirdTreeThing's Site"
theme = "hugo-ficurinia"

copyright = "Brady Norander"

paginate = 5
summaryLength = 15

[params]
    author = { name = "Brady Norander", email = "bradyn127@protonmail.com" }
    description = "WeirdTreeThing's Site"

    posts = "posts"
    showPostsLink = true

    logo = "/logo.png"
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png"
    icon512 = "/logo.png"

    showRss = true
    showTags = false

    imageInArticlePreview = true
    fitImageInArticlePreview = true
    articleSummary = true

    fontFamily = "JetBrains Mono"

    contentWidth = "1000px"
    paperCards = true
    buttonTags = true
    gridView = true
    bigArticleTitle = true
    mobileHamburgerNav = true
    enableShadow = true

[menu]
    [[menu.main]]
    identifier = "files"
    name = "Files"
    url = "https://files.tree123.org"
    weight = 1

    [[menu.main]]
    identifier = "chromebooks"
    name = "Chromebooks"
    url = "https://chromebooks.lol"
    weight = 1

    [[menu.icons]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/weirdtreething"
    weight = 1

    [[menu.icons]]
    identifier = "gitlab"
    name = "Gitlab"
    url = "https://gitlab.com/weirdtreething"
    weight = 2
